### ISSUE TITLE
New badge suggestion

### ISSUE THREAD

**Issue by PD75** [freesewing/site#132]
One badge for each completed pattern with submitted showcase + badge for all

**Comment by joostdecock** [comment]
You know what puts a real damper on my when it comes to adding badges? Having to design them. I don't particularly like graphic design, and it just feels like work ;)

But ok, you make a fair point. Having 1 single showcase badge isn't exactly very useful. Perhaps it would be better to do a per-pattern showcase badge.

I will try to come up with some new badge design that can be tweaked for all patterns so that it's sort of obvious they form a collection.

However, I will not create a badge for having all patterns because that would mean that every time I release a new pattern, I'd have to remove that badge from all of those who have it, and then potentially add it again later.

That just seems like a hassle.

**Comment by PD75** [comment]
I have some friend that have helped me with logo design before, they also like sewing, if you want I can pitch the idea and see they are up to the task. 

However I feel you almost have the badges in the pattern page.... purple also being the best color for me clothes :-)

The overall is a hassle I agree.

**Comment by joostdecock** [comment]
If your friends want to chip in some badge designs, that'd be great.

Otherwise, I can make some shitty ones, we can always update them later 😉

**Comment by joostdecock** [comment]
Cleaning up
