### ISSUE TITLE
Generate custom croquis?

### ISSUE THREAD

**Issue by vmbrasseur** [freesewing/site#133]
I'm slowly (10-30 minutes at a time, as I can find it) working through converting Hugo to a pullover hooded dress for winter work-from-home. (today I get to cut a cozy green fleece for the first draft!)

Today I was thinking that it would be nice to draw out the pattern changes I've made and/or have planned. That led me to thinking that FS already has all my measurements…so wouldn't it be possible to generate a custom croquis (either wearing one of the patterns or not) from those measurements?

It probably wouldn't be a trivial thing to do, but it would be super handy.

Anyway, just thought I'd throw that out there.

**Comment by joostdecock** [comment]
Thank your for your patience @vmbrasseur 
I am currently trying to get my new Huey pattern out the door, so I'm a bit swamped.

This custom croquis stuff is something that popped on my radar when people were raising money to have such a thing. Let's say that [I wasn't impressed](https://twitter.com/j__st/status/892416932527341568) but people somehow [threw more than 25000 dollar at these folks](https://www.kickstarter.com/projects/306275158/mybodymodel-fashion-sketch-templates-to-your-measu) (which at the current rate is about 50 years worth of donations to freesewing).

So I must admit I'm a bit *you can take your croquis and stuff them* about the entire thing ;)

I agree that this is trivial to implement in freesewing, but there's one important caveat: your measurements are no good to generate a croquis.

A croquis is a projection of your body shape on a 2D plane. The measurements you need are how wide you are at different parts of your body. But we don't measure that, we measure circumference because we want to fit a garment around that shape.

Now one could work around that in two ways:

- Ask people to measure width 
- Use the standard measurements and make some assumptions

The first option is I think too confusing for users.   
The second is a bit half-baked in my opinion, although I assume that's exactly what the MyBodyModel people are doing.

I quite frankly don't feel like implementing this. Part of me worries that it will come across as motivated by pure spite (because I made it rather obvious how I feel about that thing), the other part tells me that I have enough on my plate without giving in to feature creep.

That being said, if you want to do this, it should be pretty straightforward to do. Just design a croquis pattern, set up a freesewing instance, and you're up and running.

I'll support those who want to do this to the best of my ability, but I'm going to stay out of the croquis business for now. Hence, I'm closing this.

**Comment by joostdecock** [comment]
Oh, and just to clarify:

If you or someone else would design a croquis pattern that used that measurements that are already there and it gives good(ish) results, I'll gladly take a pull request for that and make it part of freesewing core.

All I'm saying is that I'm not going to design/coding it for you ;-)

**Comment by vmbrasseur** [comment]
While I think the "want it? do it yourself" message perhaps needed a bit softening in delivery, your reasons for not working on this for FS are great. That circumference vs width thing was something I hadn't considered.

My coding skills are very rusty and my free time more limited than any other time in my life, but if I can carve out a few moments to work a croquis pattern I will.

Thank you, @joostdecock!

**Comment by joostdecock** [comment]
Please accept my apologies, I was ranting and there was no need for that.  
Especially not to you. You've been supportive of this project from early on and deserve better. I am sorry.

If you like, you could pitch you idea on the Freesewing blog. There might be other people who would like to see this happen, and it could be a communal effort. I know a couple of people who have been toying with making their own patterns, and many hands make light work.

It's just an idea. No worries if you'd rather not.

**Comment by vmbrasseur** [comment]
Desire isn't the issue, time is. 😉 I have rather a lot of other writing projects in the works right now.

Still, I'll push this onto the stack and see whether I can't toss you a markdowned draft in the next month. Sound good?

**Comment by joostdecock** [comment]
![Excellent](https://media.giphy.com/media/8fen5LSZcHQ5O/giphy.gif)
