### ISSUE TITLE
Failed to draft theo for model xanuw

### ISSUE THREAD

**Issue by Melisaanne** [freesewing/site#162]
These links should recreate the issue:

 - [On core master branch](https://core.freesewing.org/?service=draft&bicepsCircumference=12.5&acrossBack=14.25&centerBackNeckToWaist=16&chestCircumference=36&hipsCircumference=37.75&inseam=28&naturalWaist=31.5&naturalWaistToHip=5.5&neckCircumference=14&shoulderSlope=2.5&shoulderToShoulder=17.25&shoulderToWrist=24&wristCircumference=6.25&seatCircumference=41&seatDepth=10.5&seamAllowance=imperial&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=5.8&backRise=5.8&lengthBonus=4&sa=1.525&userUnits=metric&fork=true&pattern=TheoTrousers&model=xanuw)
 - [On core develop branch](https://dev.core.freesewing.org/?service=draft&bicepsCircumference=12.5&acrossBack=14.25&centerBackNeckToWaist=16&chestCircumference=36&hipsCircumference=37.75&inseam=28&naturalWaist=31.5&naturalWaistToHip=5.5&neckCircumference=14&shoulderSlope=2.5&shoulderToShoulder=17.25&shoulderToWrist=24&wristCircumference=6.25&seatCircumference=41&seatDepth=10.5&seamAllowance=imperial&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=5.8&backRise=5.8&lengthBonus=4&sa=1.525&userUnits=metric&fork=true&pattern=TheoTrousers&model=xanuw)
 - [On core bleeding edge](https://joost.core.freesewing.org/?service=draft&bicepsCircumference=12.5&acrossBack=14.25&centerBackNeckToWaist=16&chestCircumference=36&hipsCircumference=37.75&inseam=28&naturalWaist=31.5&naturalWaistToHip=5.5&neckCircumference=14&shoulderSlope=2.5&shoulderToShoulder=17.25&shoulderToWrist=24&wristCircumference=6.25&seatCircumference=41&seatDepth=10.5&seamAllowance=imperial&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=5.8&backRise=5.8&lengthBonus=4&sa=1.525&userUnits=metric&fork=true&pattern=TheoTrousers&model=xanuw)

## Please keep the info above intact
You can include further info and comments here

**Comment by joostdecock** [comment]
Thank you for reaching out.

Your issue is caused because you entered your measurements in imperial, yet your settings are metric.

So when you say 1 inch, that means 1cm, and things go off the rails because your measurements are not realistic.

Please change your units both for your profile and your model:

 - To change your profile units, go to [your account](https://freesewing.org/account) click **Settings** and switch the units to imperial.
 - To change your model's units, go to [the model's page](https://freesewing.org/models/xanuw ), click **Settings** and switch the units to imperial
