### ISSUE TITLE
Spelling error - Patterns Page

### ISSUE THREAD

**Issue by theUnmutual** [freesewing/site#206]
Huey 

It reads "optinal". Should read "optional"

**Comment by joostdecock** [comment]
Thanks for reporting this. If you let me know your username on the site, I'll assign you the issue badge for it.

As for the typo, it's part of the config file, so it's been fixed in core: https://github.com/freesewing/core/commit/347cab5d3e71e2d2c5e70d76313536c054cfe611

I won't cut a new release just for this, but I've got some changes to be rolled out next weekend, so it will appear at that time.
