### ISSUE TITLE
Problem with draft krytp

### ISSUE THREAD

**Issue by LarrySchild** [freesewing/site#323]
See [here](https://freesewing.org/drafts/krytp)

Hi, this is my first pattern drafted here.
In the Hugo hoodie, the sleeves seem t\li2ke they would be short.  I'm usually pretty long in the sleeves.
I'm pretty sure I was measured correctly.

Thanks!

**Comment by joostdecock** [comment]
Based on your measurements, that seems ok to me. Did you take into account that there's still ribbing to be attached at the wrist?

You can redraft using the paperless pattern so that you can check the exact measurements before printing. But I suspect it's actually fine.

Please let me know how it goes, I'll keep this open until then.

**Comment by LarrySchild** [comment]
Thanks for the reply.  I'll print it out and take a look.
