### ISSUE TITLE
Valid Entry required error on entry of measurement

### ISSUE THREAD

**Issue by Katesfolly** [freesewing/site#43]
When entering a value (30.5 cm) into the bicep measurement for a model, I received a invalid entry error, and can't figure out why.

![screen shot 2017-07-21 at 3 06 30 pm](https://user-images.githubusercontent.com/30324809/28480523-ae0baf3c-6e26-11e7-84fb-f3b25ef199d2.png)

**Comment by joostdecock** [comment]
This was caused by the input type now being number. It seems that for some browsers, that means integers only unless you specifically configure it otherwise.
It's fixes now. If you still experience the problem, open [this url](https://dev.freesewing.org/components/measurement/settings-metric) and force a reload from the server (ctrl-shift reload) to update the input field.

Thanks for reporting this, great work 👍
