### ISSUE TITLE
Simon Shirt custom seam allowance wonky

### ISSUE THREAD

**Issue by nutation** [freesewing/site#666]
<img width="1276" alt="Screen Shot 2019-08-18 at 3 24 36 PM" src="https://user-images.githubusercontent.com/1268923/63231177-d0146f00-c1cc-11e9-9d67-3321303ce9a1.png">

Just found this redrafting simon

**Comment by joostdecock** [comment]
This is fixed in the new version:

![sa](https://user-images.githubusercontent.com/1708494/63241619-ad2d9d80-c254-11e9-86fe-4dbf7b9c8117.png)

Since our planned release date for the new website is 6 days from now, I'm not going to fix this in the *old* website, but instead try to get the new one out the door in time :smile:
