### ISSUE TITLE
Problem with draft anvfz

### ISSUE THREAD

**Issue by vmbrasseur** [freesewing/site#83]
See [here](https://freesewing.org/drafts/anvfz)

Now, the measurements *may* need work, but that's a hardware problem (my solo measuring skills) and not relevant.

What *is* relevant are those bodice pieces, there where the side seams meet the under arm. What's up with that little curlicue? It looks like the under arm curve got a bit confused as it approached the side seam.

**Comment by joostdecock** [comment]
Your across back measurement seems incorrect.

You have it measured as being higher than your shoulder to shoulder, and more than 50% of your chest circumference. Both of those are practically impossible.

Here's the documentation for the across back measurement: https://freesewing.org/docs/measurements/acrossback

Arguably, it's very difficult to measure on yourself. If you want, just enter 95% of your shoulder o shoulder measurement. It's always more or less that, and it's not that crucial for Hugo anyway because of the raglan sleeve design.

Update the model, the redraft, and let me know how it went 😉

**Comment by vmbrasseur** [comment]
You are, of course, very correct. That back measurement was, like, whoa, so wrong. I did bad math when I measured.

That's now corrected, as are a few other measurements (I discovered a problem w/my measuring tape, of all things). The [redraft is here](https://freesewing.org/drafts/ystzg#draft-container) and it looks much more reasonable now.

Thanks for the help, @joostdecock! 🏆

**Comment by joostdecock** [comment]
That's great to hear 😀
Just in case you are doing math to convert from imperial to metric: imperial is fully supported. Change it in your account settings, and in your model's settings.
(Models can be different but default to the account units)

Just in case 😉

**Comment by vmbrasseur** [comment]
Nah, the problem was that I subtracted wrong. 😊
